Add contribution links within context #1000 #1001
nhsuk/nhsuk-service-manual pull request #1073
Opened 2021-03-24 13:41 UTC by Tosin-Balogun

## Description

This is a prototype based on improving the users access to our contribution process through the service manual website

We will use this pull request to review changes, updates et al
### Related issue

#1000 #1001 
## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry
- [ ] Page updated date

2021-03-24 13:46 UTC, Tosin-Balogun commented
The conclusion was to see if we can repurpose the 'get in touch' partial to host the contextual links idea. We would need to restyle and rewrite it based on the evidence we have discovered

@davidhunter08 - The above is correct, yes?
@sarawilcox @nancyhalladay24 
<img width="1260" alt="Screenshot 2021-03-23 at 17 14 48" src="https://user-images.githubusercontent.com/71393402/112320580-0bc7c280-8ca7-11eb-8727-afa62ac09fe2.png">

2021-03-30 08:37 UTC, davidhunter08 commented on app/views/includes/_contact-panel.njk
> +<p>If you have any questions, you can <a href="https://service-manual.nhs.uk/slack">reach out to our community forum on Slack</a> or <a href="mailto:service-manual@nhs.net">contact us via email</a>.
"via email" or "by email"?

2021-03-30 08:41 UTC, Tosin-Balogun commented on app/views/includes/_contact-panel.njk
> +<p>If you have any questions, you can <a href="https://service-manual.nhs.uk/slack">reach out to our community forum on Slack</a> or <a href="mailto:service-manual@nhs.net">contact us via email</a>.
@sarawilcox - What do you reckon? Is the word 'via' not as accessible as 'by'?

2021-03-30 08:44 UTC, davidhunter08 requested changes

2021-03-30 08:44 UTC, davidhunter08 commented on app/views/includes/_contact-panel.njk
> +<p>Before you start, you will need a <a href="https://github.com/join?source=login">GitHub account</a>, It's an open forum where we collect feedback</p>
small "i" needed on "it's an open forum..."

2021-03-30 09:35 UTC, sarawilcox reviewed
Hi Tosin, could you please make this 2 sentences. It should read: 
<p>Before you start, you will need a <a href="https://github.com/join?source=login">GitHub account</a>. It's an open forum where we collect feedback.</p>

2021-03-30 09:37 UTC, Tosin-Balogun commented
> Hi Tosin, could you please make this 2 sentences. It should read:
> 
> Before you start, you will need a [GitHub account](https://github.com/join?source=login). It's an open forum where we collect feedback.

Done ✅

2021-03-30 09:38 UTC, sarawilcox approved these changes
Thanks Tosin.

2021-03-30 09:42 UTC, merged

2021-03-30 11:53 UTC, Tosin-Balogun commented
@DomBaker - this one