Expander - when not to use content update
nhsuk/nhsuk-service-manual pull request #1811
Opened 2022-10-13 13:04 UTC by wa-rren-dev

## Description

### Related issue

## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry
- [ ] Page updated date

2022-10-14 15:58 UTC, sarawilcox approved these changes
Yes, this is fine. Thanks v much!

2022-10-18 08:59 UTC, mcheung-nhs requested changes

2022-10-18 08:59 UTC, mcheung-nhs commented on app/views/design-system/components/expander/index.njk
> +    <li>if only some of your users will need the information - use details</a> instead</li>
Random close `</a>` here?

2022-10-18 13:28 UTC, wa-rren-dev commented on app/views/design-system/components/expander/index.njk
> +    <li>if only some of your users will need the information - use details</a> instead</li>
Good spot! Was testing you

2022-10-18 15:20 UTC, mcheung-nhs approved these changes

2022-10-19 13:13 UTC, merged