Import and initialise error summary JS and set focusOnPageLoad to false
nhsuk/nhsuk-service-manual pull request #1886
Opened 2023-05-22 12:27 UTC by the-nathan-smith

## Description
Import and initialise error summary JS and set focusOnPageLoad to false so that the Error Summary examples work as expected.

### Related issue
Resolves NHSUK Frontend Issue [#766](https://github.com/nhsuk/nhsuk-frontend/issues/766).

## Checklist
- [x] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [x] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [x] CHANGELOG entry
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry
- [ ] Page updated date

2023-05-22 12:34 UTC, andymantell requested changes

2023-05-22 12:34 UTC, andymantell commented on app/scripts/main.js
> +import ErrorSummary from '../../node_modules/nhsuk-frontend/packages/components/error-summary/error-summary';
Can this import path be the same format as the ones above it? I.e. remove the `../..`

2023-05-22 12:35 UTC, andymantell commented on app/scripts/main.js
> +import ErrorSummary from '../../node_modules/nhsuk-frontend/packages/components/error-summary/error-summary';
Actually, this is throwing a linting error anyway - see the pipeline failures

2023-05-22 12:35 UTC, andymantell requested changes
The pipeline is failing with eslint errors. You can run these locally with `npm run lint`

2023-05-22 12:45 UTC, the-nathan-smith commented on app/scripts/main.js
> +import ErrorSummary from '../../node_modules/nhsuk-frontend/packages/components/error-summary/error-summary';
Fixed this issue, Azure pipeline is now passing.

2023-05-23 12:32 UTC, andymantell approved these changes

2023-05-23 12:36 UTC, merged