Mention nhsuk-javascript does the focusing of the error summary
nhsuk/nhsuk-service-manual pull request #1980
Opened 2024-05-29 14:50 UTC by edwardhorsford

## Description
The guidance for errorSummary says that you need to focus the error summary on page load - but doesn't mention that the nhsuk-frontend javascript will do this for you - most services shouldn't need to do anything. Adding this text should hopefully make that clearer.

2024-06-05 19:22 UTC, frankieroberto requested changes

2024-06-05 19:22 UTC, frankieroberto commented on app/views/design-system/components/error-summary/index.njk
> +      <li>move the keyboard focus to the error summary (the nhsuk-frontend javascript will do this for you)</li>
Convention on [this page](https://service-manual.nhs.uk/design-system/production) seems to be to use "NHS.UK frontend"?

```suggestion
      <li>move the keyboard focus to the error summary (the NHS.UK frontend javascript will do this for you)</li>
```

2024-06-06 09:48 UTC, frankieroberto approved these changes

2024-06-06 11:57 UTC, sarawilcox reviewed
Hi Ed, could you reword to say "NHS.UK frontend JavaScript", please. To match how we talk about JavaScript elsewhere. Thanks a lot.

2024-06-06 11:58 UTC, sarawilcox reviewed
We usually write it as JavaScript. Would you mind tweaking, please Ed.

2024-06-06 12:15 UTC, edwardhorsford commented on app/views/design-system/components/error-summary/index.njk
> +      <li>move the keyboard focus to the error summary (the NHS.UK frontend javascript will do this for you)</li>
```suggestion
      <li>move the keyboard focus to the error summary (the NHS.UK frontend JavaScript will do this for you)</li>
```

2024-06-06 12:51 UTC, frankieroberto approved these changes

2024-06-06 13:02 UTC, sarawilcox approved these changes
Thanks Ed!

2024-06-06 13:19 UTC, merged